version: '3.8'

services:
  web:
    build:
      context: ./
    command: web
    env_file:
      - .env.web
    volumes:
#      - static:/opt/app/public/static
      - ./public:/opt/app/public

    environment:
      DEBUG: "True"
    restart: always
    depends_on:
      - postgres

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
#      - static:/opt/app/public/static
      - ./public:/opt/app/public

  redis:
    image: "redis:alpine"

  postgres:
    image: postgres
    restart: always
    shm_size: '256mb'
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: simple_tasks
      POSTGRES_USER: simple_tasks
      POSTGRES_PASSWORD: simple_tasks

volumes:
  db:
  static:
#  public:
#    driver: local
#    driver_opts:
#      o: bind
#      type: none
#      device: ${PWD}/public